# Redirects
[[redirects]]
  from = "/subdirectory/*"
  to = "/subdirectory/index.html"
  status = 200

# Rewrites
[[redirects]]
  from = "/subdirectory/index.html"
  to = "/subdirectory"
  status = 200

