# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Additional Settings (Optional)
[build]
  command = "npm run build"  # Specify the build command for your project
  publish = "dist"          # Specify the directory to publish (where your built files are located)
