# Redirects and Rewrites Configuration for Netlify

# Redirects
[[redirects]]
  from = "/subdirectory/*"
  to = "/subdirectory/index.html"
  status = 200

# Rewrites
[[redirects]]
  from = "/subdirectory/index.html"
  to = "/subdirectory"
  status = 200

# Add more redirects or rewrites as needed...

# Additional Settings (Optional)
[build]
  command = "npm run build"  # Specify the build command for your project
  publish = "build"          # Specify the directory to publish (where your built files are located)
